#!/usr/bin/env bash
function gvm_export_path() {
	export PATH="$GVM_ROOT/bin:$(echo "$PATH" | ${TR_PATH:-tr} ":" "\n" | "${GREP_PATH:-grep}" -v '^$' | ${EGREP_PATH:-egrep} -v "$GVM_ROOT/(pkgsets|gos|bin)" | ${TR_PATH:-tr} "\n" ":" | ${SED_PATH:-sed} 's/:*$//')"
	export GVM_PATH_BACKUP="$PATH"
}

